### ISSUE TITLE
Fields in options?

### ISSUE THREAD

**Issue by reagle** [STealthy-and-haSTy/EnhancedSnippets#3]
Thank you for this! Awesome to see this working!

Can we have fields in options? For example, the following is a markdown snippet for an iframe where the user can select the dimensions as well as an optional time clip start/end specification and, if used, it'd be nice to be able to tab to those fields.

```
---
tabTrigger: ",ty"
scope: "text.html.markdown"
description: "ESS Youtube embed"
options:
  - field: 1
    placeholder: 'dimensions'
    values:
      - width="853" height="480"
      - width="700" height="394"
      - width="560" height="315"
      - width="315" height="560"
  - field: 2
    placeholder: time
    values:
      - ""
      - "&amp;start=${3:60}&amp;end=${4:120}"
---

<iframe $1 src="https://www.youtube.com/embed/$0?rel=0$2 allowfullscreen></iframe>
```
