### ISSUE TITLE
Unwanted space and descriptions in options?

### ISSUE THREAD

**Issue by reagle** [STealthy-and-haSTy/EnhancedSnippets#6]
I have the following snippet and wonder if there was a way to have the comments show in the pop-up selector? Also, selecting one of those values creates and unwanted space before the parens: `raiseValueError ("")`:

```
---
tabTrigger: "rai"
scope: "source.python"
description: "raise Exceptions in Python"
options:
  - field: 1
    placeholder: "common exceptions"
    values:
      - "ValueError"  # a function receives an argument of the correct type but an inappropriate value.
      - "TypeError"  # an operation or function is applied to an object of an inappropriate type.
      - "IndexError"  # a sequence subscript (index) is out of range.
      - "KeyError"  # a dictionary key is not found.
      - "FileNotFoundError"  # a file or directory is requested but doesn't exist.
      - "IOError"  # an I/O operation fails, such as print() function or the open() function.
      - "AttributeError"  # an attribute reference or assignment fails.
      - "ImportError"  # the import statement can't find the module definition or when a from ... import fails.
      - "ZeroDivisionError"  # the second argument of a division or modulo operation is zero.
      - "RuntimeError"  # an error is detected that doesn't fall in any of the other categories.
      - "NotImplementedError"  # an abstract method that needs to be implemented in an inherited class is not actually implemented.
---

raise$1("$0")
```

**Comment by OdatNurd** [comment]
The code that loads the options doesn't do as much validation as it could at the moment, but a space in there seems wacky, I will look into that.

Regarding the other question, the comments don't get provided to me via the library but the data layout could totally be extended to include a way to add such information, which seems like it would be quite useful.

**Comment by OdatNurd** [comment]
We're currently looking into the extra space bug while I'm live, but I can't replicate your result; it inserts at I would expect it to.

Have you tried this in safe mode? Perhaps there is some extra plugin or setting that's triggering this to happen that we can nail down.

**Comment by OdatNurd** [comment]
Regarding the second item, some changes will be pushed up shortly that accomplish something like what you're asking for here, but handled in a slightly different way.

Given a snippet like:

```yaml
---
tabTrigger: "rai"
scope: "source.python"
description: "raise Exceptions in Python"
options:
  - field: 1
    placeholder: "common exceptions"
    values:
      - text: "ValueError"
        details: "a function receives an argument of the correct type but an inappropriate value."
      - text: "TypeError"
        details: "an operation or function is applied to an object of an inappropriate type."
      - text: "IndexError"
        details: "a sequence subscript (index) is out of range."
      - text: "KeyError"
        details: "a dictionary key is not found."
      - text: "FileNotFoundError"
        details: "a file or directory is requested but doesn't exist."
      - text: "IOError"
        details: "an I/O operation fails, such as print() function or the open() function."
      - text: "AttributeError"
        details: "an attribute reference or assignment fails."
      - text: "ImportError"
        details: "the import statement can't find the module definition or when a from ... import fails."
      - text: "ZeroDivisionError"
        details: "the second argument of a division or modulo operation is zero."
      - text: "RuntimeError"
        details: "an error is detected that doesn't fall in any of the other categories."
      - text: "NotImplementedError"
        details: "an abstract method that needs to be implemented in an inherited class is not actually implemented."

---

raise$1("$0")
```

The result when the snippet expands and the field gets hit is:

![image](https://github.com/STealthy-and-haSTy/EnhancedSnippets/assets/13212876/c2c66b96-3fb4-4747-9d8d-d1035736f0d5)

This is not currently documented, and it works only for YAML snippets at the moment. Older snippets will still work, and you can mix and match. Options that you pass for values can be either a set of text and details keys, or just a singe string as previous, as desired.

I'm going to mark this one as closed for the time being (more work will be done on this); can you please create a new issue that covers the extra space issue? I can't replicate that one locally and I don't want to hold this issue open in the interim.
